# This file is part of json-append.
# https://github.com/SeedyROM/json-append

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2017, Zack Kollar <zackkollar@gmail.com>

language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make lint
    - make test
